"""Add RAG entities

Revision ID: 37172d7f9898
Revises: 5ecc7502737f
Create Date: 2025-11-05 02:37:43.501304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37172d7f9898'
down_revision: Union[str, None] = '5ecc7502737f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ragingestionstatus = sa.Enum(
    'PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED',
    name='ragingestionstatus'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'artifact_versions' not in existing_tables:
        op.create_table('artifact_versions',
        sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('artifact_id', sa.Integer(), nullable=False),
        sa.Column('job_run_id', sa.Integer(), nullable=True, comment='Job that created this version'),
        sa.Column('content_locator', sa.String(length=1000), nullable=False, comment='Storage location (file path or database reference)'),
        sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of content (for deduplication)'),
        sa.Column('metadata', sa.JSON(), nullable=False, comment='Generation metadata (schema_version, llm_provider, model, prompt_template, tokens, cost)'),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.job_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('version_id')
        )
        op.create_index('idx_artifact_version_artifact', 'artifact_versions', ['artifact_id'], unique=False)
        op.create_index('idx_artifact_version_hash', 'artifact_versions', ['content_hash'], unique=False)
        op.create_index('idx_artifact_version_is_current', 'artifact_versions', ['is_current', 'artifact_id'], unique=False)
        op.create_index('idx_artifact_version_job_run', 'artifact_versions', ['job_run_id'], unique=False)

    if 'artifacts' not in existing_tables:
        op.create_table('artifacts',
        sa.Column('artifact_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('artifact_key', sa.String(length=500), nullable=False, comment="Composite key: {kind}:{project}:{identifier} (e.g., 'summary:project-alpha:meeting-123')"),
        sa.Column('artifact_kind', sa.String(length=100), nullable=False, comment='Artifact type (summary, decisions_index, entities_index, timeline, action_items, custom)'),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('current_version_id', sa.Integer(), nullable=True, comment='Reference to latest ArtifactVersion'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['current_version_id'], ['artifact_versions.version_id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('artifact_id'),
        sa.UniqueConstraint('artifact_key')
        )
        op.create_index('idx_artifact_current_version', 'artifacts', ['current_version_id'], unique=False)
        op.create_index('idx_artifact_kind', 'artifacts', ['artifact_kind'], unique=False)
        op.create_index('idx_artifact_project', 'artifacts', ['project_id'], unique=False)

    if 'backfill_jobs' not in existing_tables:
        op.create_table('backfill_jobs',
        sa.Column('backfill_job_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('target_folder_path', sa.String(length=1000), nullable=True, comment='Folder path for bulk processing'),
        sa.Column('target_file_list', sa.JSON(), nullable=True, comment='List of specific file IDs to process'),
        sa.Column('total_file_count', sa.Integer(), nullable=False),
        sa.Column('processed_count', sa.Integer(), nullable=False),
        sa.Column('failed_count', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='backfillstatus'), nullable=False),
        sa.Column('progress_percentage', sa.Float(), nullable=True),
        sa.Column('summary_report', sa.JSON(), nullable=True, comment='Success/failure breakdown, artifacts created, cost estimates'),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('paused_at', sa.DateTime(), nullable=True),
        sa.Column('resumed_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('failed_count >= 0', name='failed_count_non_negative'),
        sa.CheckConstraint('processed_count >= 0', name='processed_count_non_negative'),
        sa.CheckConstraint('progress_percentage IS NULL OR (progress_percentage >= 0.0 AND progress_percentage <= 100.0)', name='valid_progress'),
        sa.CheckConstraint('total_file_count >= 0', name='total_count_non_negative'),
        sa.PrimaryKeyConstraint('backfill_job_id')
        )
        op.create_index('idx_backfill_started', 'backfill_jobs', ['started_at'], unique=False)
        op.create_index('idx_backfill_status', 'backfill_jobs', ['status'], unique=False)

    if 'files' not in existing_tables:
        op.create_table('files',
        sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('relative_path', sa.String(length=1000), nullable=False, comment='Relative path from project root or identifier'),
        sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type (e.g., application/pdf, text/markdown)'),
        sa.Column('source_type', sa.Enum('MEETING', 'UPLOADED_DOCUMENT', 'CHAT_EXPORT', name='filesourcetype'), nullable=False, comment='Source classification (meeting, uploaded_document, chat_export)'),
        sa.Column('project_id', sa.Integer(), nullable=False, comment='Project this file belongs to'),
        sa.Column('current_version_id', sa.Integer(), nullable=True, comment='Current active version of this file'),
        sa.Column('deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['current_version_id'], ['file_versions.version_id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('file_id')
        )
        op.create_index('idx_file_current_version', 'files', ['current_version_id'], unique=False)
        op.create_index('idx_file_deleted', 'files', ['deleted'], unique=False)
        op.create_index('idx_file_project', 'files', ['project_id'], unique=False)
        op.create_index('idx_file_relative_path', 'files', ['relative_path'], unique=False)
        op.create_index('idx_file_source_type', 'files', ['source_type'], unique=False)

    if 'file_versions' not in existing_tables:
        op.create_table('file_versions',
        sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of file content for change detection'),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='File size in bytes'),
        sa.Column('content_locator', sa.String(length=1000), nullable=False, comment='Path or URI to access file content'),
        sa.Column('is_current', sa.Boolean(), nullable=False, comment='Whether this is the current active version'),
        sa.Column('discovered_at', sa.DateTime(), nullable=False, comment='When this version was first discovered/created'),
        sa.CheckConstraint('file_size_bytes > 0', name='file_size_positive'),
        sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('version_id')
        )
        op.create_index('idx_file_version_file', 'file_versions', ['file_id'], unique=False)
        op.create_index('idx_file_version_hash', 'file_versions', ['content_hash'], unique=False)
        op.create_index('idx_file_version_is_current', 'file_versions', ['is_current', 'file_id'], unique=False)

    if 'artifact_links' not in existing_tables:
        op.create_table('artifact_links',
        sa.Column('link_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('artifact_version_id', sa.Integer(), nullable=False),
        sa.Column('file_version_id', sa.Integer(), nullable=False),
        sa.Column('role_type', sa.Enum('SOURCE', 'DERIVED', 'REFERENCE', name='linkroletype'), nullable=False, comment='Relationship type between artifact and file'),
        sa.Column('contribution_weight', sa.Float(), nullable=True, comment="Weight of this file's contribution to the artifact (0.0-1.0)"),
        sa.Column('link_metadata', sa.JSON(), nullable=True, comment='Additional link metadata (chunks used, relevance scores, etc.)'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('contribution_weight IS NULL OR (contribution_weight >= 0.0 AND contribution_weight <= 1.0)', name='valid_weight'),
        sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.version_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['file_version_id'], ['file_versions.version_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('link_id')
        )
        op.create_index('idx_artifact_link_artifact', 'artifact_links', ['artifact_version_id'], unique=False)
        op.create_index('idx_artifact_link_file', 'artifact_links', ['file_version_id'], unique=False)
        op.create_index('idx_artifact_link_role', 'artifact_links', ['role_type'], unique=False)
        op.create_index('idx_artifact_link_unique', 'artifact_links', ['artifact_version_id', 'file_version_id'], unique=True)

    if 'chunks' not in existing_tables:
        op.create_table('chunks',
        sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_version_id', sa.Integer(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Sequential index within the file version'),
        sa.Column('text_content', sa.Text(), nullable=False, comment='The actual text content of this chunk'),
        sa.Column('char_offset_start', sa.Integer(), nullable=False, comment='Character offset start in original document'),
        sa.Column('char_offset_end', sa.Integer(), nullable=False, comment='Character offset end in original document'),
        sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata (speaker, timestamp, page number, etc.)'),
        sa.Column('deleted', sa.Boolean(), nullable=False, comment='Soft delete flag for audit trail'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('char_offset_end > char_offset_start', name='valid_offsets'),
        sa.CheckConstraint('char_offset_start >= 0', name='char_offset_start_non_negative'),
        sa.CheckConstraint('chunk_index >= 0', name='chunk_index_non_negative'),
        sa.ForeignKeyConstraint(['file_version_id'], ['file_versions.version_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('chunk_id')
        )
        op.create_index('idx_chunk_deleted', 'chunks', ['deleted'], unique=False)
        op.create_index('idx_chunk_file_version', 'chunks', ['file_version_id'], unique=False)
        op.create_index('idx_chunk_index', 'chunks', ['file_version_id', 'chunk_index'], unique=False)

    if 'job_runs' not in existing_tables:
        op.create_table('job_runs',
        sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('pipeline_name', sa.String(length=100), nullable=False, comment='Rule name that triggered this job'),
        sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='jobrunstatus'), nullable=False),
        sa.Column('input_file_version_id', sa.Integer(), nullable=True, comment='Source file version (null for backfill aggregates)'),
        sa.Column('backfill_job_id', sa.Integer(), nullable=True, comment='Parent backfill job if part of batch'),
        sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
        sa.Column('metrics', sa.JSON(), nullable=True, comment='Job metrics (chunks_created, embeddings_generated, artifacts_produced, llm_tokens, cost)'),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('retry_count >= 0', name='retry_count_non_negative'),
        sa.ForeignKeyConstraint(['backfill_job_id'], ['backfill_jobs.backfill_job_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['input_file_version_id'], ['file_versions.version_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('job_id')
        )
        op.create_index('idx_job_run_backfill', 'job_runs', ['backfill_job_id'], unique=False)
        op.create_index('idx_job_run_file_version', 'job_runs', ['input_file_version_id'], unique=False)
        op.create_index('idx_job_run_pipeline', 'job_runs', ['pipeline_name'], unique=False)
        op.create_index('idx_job_run_started', 'job_runs', ['started_at'], unique=False)
        op.create_index('idx_job_run_status', 'job_runs', ['status'], unique=False)

    if 'embeddings' not in existing_tables:
        op.create_table('embeddings',
        sa.Column('embedding_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('chunk_id', sa.Integer(), nullable=False),
        sa.Column('embedding_model', sa.String(length=100), nullable=False, comment='Model used to generate embedding (e.g., text-embedding-3-large)'),
        sa.Column('vector_db_id', sa.String(length=255), nullable=False, comment='ID in ChromaDB for vector retrieval'),
        sa.Column('collection_name', sa.String(length=100), nullable=False, comment='ChromaDB collection name'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('embedding_id'),
        sa.UniqueConstraint('chunk_id')
        )
        op.create_index('idx_embedding_collection', 'embeddings', ['collection_name'], unique=False)
        op.create_index('idx_embedding_model', 'embeddings', ['embedding_model'], unique=False)
        op.create_index('idx_embedding_vector_db_id', 'embeddings', ['vector_db_id'], unique=False)

    if 'job_steps' not in existing_tables:
        op.create_table('job_steps',
        sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('job_run_id', sa.Integer(), nullable=False),
        sa.Column('step_name', sa.String(length=100), nullable=False, comment='Step identifier (normalize, chunk, embed, generate_{artifact_kind})'),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstepstatus'), nullable=False),
        sa.Column('log_output', sa.JSON(), nullable=True, comment='Structured log output with key execution details'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if step failed'),
        sa.Column('error_type', sa.String(length=100), nullable=True, comment='Error type/class name for categorization'),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.job_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('step_id')
        )
        op.create_index('idx_job_step_job_run', 'job_steps', ['job_run_id'], unique=False)
        op.create_index('idx_job_step_name', 'job_steps', ['step_name'], unique=False)
        op.create_index('idx_job_step_status', 'job_steps', ['status'], unique=False)
    meeting_columns = {column['name'] for column in inspector.get_columns('meetings')}
    if 'file_id' not in meeting_columns:
        op.add_column(
            'meetings',
            sa.Column(
                'file_id',
                sa.Integer(),
                nullable=True,
                comment='Link to File entity for RAG processing',
            ),
        )
    if 'rag_ingestion_status' not in meeting_columns:
        op.add_column(
            'meetings',
            sa.Column(
                'rag_ingestion_status',
                ragingestionstatus,
                nullable=True,
                comment='Status of RAG ingestion for this meeting',
            ),
        )

    existing_meeting_indexes = {index['name'] for index in inspector.get_indexes('meetings')}
    if 'idx_meeting_file_id' not in existing_meeting_indexes:
        op.create_index('idx_meeting_file_id', 'meetings', ['file_id'])
    if 'idx_meeting_rag_status' not in existing_meeting_indexes:
        op.create_index('idx_meeting_rag_status', 'meetings', ['rag_ingestion_status'])
    op.add_column('projects', sa.Column('display_name', sa.String(length=255), nullable=True, comment='Human-readable project name for UI display'))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True, comment='Project description'))
    op.add_column('projects', sa.Column('ingestion_folder_path', sa.String(length=500), nullable=True, comment='Local filesystem path for document ingestion'))
    op.add_column('projects', sa.Column('artifact_retention_days', sa.Integer(), nullable=True, comment='Retention policy for artifacts (null = indefinite)'))
    op.add_column('projects', sa.Column('metadata', sa.JSON(), nullable=True, comment='Custom metadata (team, client, domain tags)'))
    op.create_index('idx_project_ingestion_folder', 'projects', ['ingestion_folder_path'], unique=False)
    op.create_index('idx_project_is_default', 'projects', ['is_default'], unique=False)
    op.add_column('transcripts', sa.Column('deepgram_response', sa.JSON(), nullable=True, comment='Raw Deepgram API response with utterances and speaker metadata'))
    op.add_column('transcripts', sa.Column('chunk_count', sa.Integer(), nullable=True, comment='Number of chunks created from this transcript'))
    op.add_column('transcripts', sa.Column('embedding_generated_at', sa.DateTime(), nullable=True, comment='Timestamp when embeddings were generated'))
    op.create_index('idx_transcript_embedding_generated', 'transcripts', ['embedding_generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcript_embedding_generated', table_name='transcripts')
    op.drop_column('transcripts', 'embedding_generated_at')
    op.drop_column('transcripts', 'chunk_count')
    op.drop_column('transcripts', 'deepgram_response')
    op.drop_index('idx_project_is_default', table_name='projects')
    op.drop_index('idx_project_ingestion_folder', table_name='projects')
    op.drop_column('projects', 'metadata')
    op.drop_column('projects', 'artifact_retention_days')
    op.drop_column('projects', 'ingestion_folder_path')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'display_name')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_index('idx_meeting_rag_status', table_name='meetings')
    op.drop_index('idx_meeting_file_id', table_name='meetings')
    op.drop_column('meetings', 'rag_ingestion_status')
    ragingestionstatus.drop(op.get_bind(), checkfirst=True)
    op.drop_column('meetings', 'file_id')
    op.drop_index('idx_job_step_status', table_name='job_steps')
    op.drop_index('idx_job_step_name', table_name='job_steps')
    op.drop_index('idx_job_step_job_run', table_name='job_steps')
    op.drop_table('job_steps')
    op.drop_index('idx_embedding_vector_db_id', table_name='embeddings')
    op.drop_index('idx_embedding_model', table_name='embeddings')
    op.drop_index('idx_embedding_collection', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('idx_job_run_status', table_name='job_runs')
    op.drop_index('idx_job_run_started', table_name='job_runs')
    op.drop_index('idx_job_run_pipeline', table_name='job_runs')
    op.drop_index('idx_job_run_file_version', table_name='job_runs')
    op.drop_index('idx_job_run_backfill', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('idx_chunk_index', table_name='chunks')
    op.drop_index('idx_chunk_file_version', table_name='chunks')
    op.drop_index('idx_chunk_deleted', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_artifact_link_unique', table_name='artifact_links')
    op.drop_index('idx_artifact_link_role', table_name='artifact_links')
    op.drop_index('idx_artifact_link_file', table_name='artifact_links')
    op.drop_index('idx_artifact_link_artifact', table_name='artifact_links')
    op.drop_table('artifact_links')
    op.drop_index('idx_file_source_type', table_name='files')
    op.drop_index('idx_file_relative_path', table_name='files')
    op.drop_index('idx_file_project', table_name='files')
    op.drop_index('idx_file_deleted', table_name='files')
    op.drop_index('idx_file_current_version', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_file_version_is_current', table_name='file_versions')
    op.drop_index('idx_file_version_hash', table_name='file_versions')
    op.drop_index('idx_file_version_file', table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index('idx_backfill_status', table_name='backfill_jobs')
    op.drop_index('idx_backfill_started', table_name='backfill_jobs')
    op.drop_table('backfill_jobs')
    op.drop_index('idx_artifact_project', table_name='artifacts')
    op.drop_index('idx_artifact_kind', table_name='artifacts')
    op.drop_index('idx_artifact_current_version', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_artifact_version_job_run', table_name='artifact_versions')
    op.drop_index('idx_artifact_version_is_current', table_name='artifact_versions')
    op.drop_index('idx_artifact_version_hash', table_name='artifact_versions')
    op.drop_index('idx_artifact_version_artifact', table_name='artifact_versions')
    op.drop_table('artifact_versions')
    # ### end Alembic commands ###
