"""Meeting-specific chunking strategy that preserves speaker boundaries.

This module implements chunking for meeting transcripts generated by Deepgram.
It combines utterances intelligently while preserving speaker metadata and
never splitting mid-utterance to maintain context integrity.
"""

from typing import List

from src.services.chunking.base import ChunkingStrategy, ChunkResult


class MeetingChunker(ChunkingStrategy):
    """Chunks meeting transcripts while preserving speaker boundaries.

    This chunker is specifically designed for Deepgram transcription output
    with speaker diarization. It combines consecutive utterances until the
    chunk_size is reached, but NEVER splits within an utterance. This ensures
    that speaker context remains intact and each chunk represents complete
    thoughts.

    Key Features:
        - Preserves speaker boundaries (never splits mid-utterance)
        - Combines utterances until chunk_size reached
        - Handles utterances longer than chunk_size gracefully
        - Creates chunk_overlap by repeating last utterances
        - Extracts and formats speaker metadata and timestamps

    Args:
        chunk_size: Target maximum characters per chunk (default: 1200)
        chunk_overlap: Number of characters to overlap between chunks (default: 200)

    Example:
        >>> deepgram_response = {
        ...     "results": {
        ...         "utterances": [
        ...             {
        ...                 "speaker": 0,
        ...                 "start": 0.5,
        ...                 "end": 5.2,
        ...                 "transcript": "Hello everyone, let's start the meeting."
        ...             },
        ...             {
        ...                 "speaker": 1,
        ...                 "start": 5.8,
        ...                 "end": 12.3,
        ...                 "transcript": "Thanks for joining. Today we'll discuss..."
        ...             }
        ...         ]
        ...     }
        ... }
        >>> chunker = MeetingChunker(chunk_size=1200, chunk_overlap=200)
        >>> chunks = chunker.chunk_from_deepgram(deepgram_response)
        >>> print(chunks[0].metadata)
        {'speaker': 'Speaker 0', 'timestamp': '00:00:00', 'speaker_name': None}
    """

    def __init__(self, chunk_size: int = 1200, chunk_overlap: int = 200):
        """Initialize the meeting chunker.

        Args:
            chunk_size: Target maximum characters per chunk. Defaults to 1200
                which provides good context for embeddings while staying within
                typical model limits.
            chunk_overlap: Number of overlapping characters between consecutive
                chunks. Defaults to 200 to maintain context across boundaries.

        Raises:
            ValueError: If chunk_size <= 0 or chunk_overlap < 0 or
                chunk_overlap >= chunk_size
        """
        if chunk_size <= 0:
            raise ValueError(f"chunk_size must be positive, got {chunk_size}")
        if chunk_overlap < 0:
            raise ValueError(f"chunk_overlap must be non-negative, got {chunk_overlap}")
        if chunk_overlap >= chunk_size:
            raise ValueError(
                f"chunk_overlap ({chunk_overlap}) must be less than "
                f"chunk_size ({chunk_size})"
            )

        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

    def chunk(self, text: str, source_metadata: dict = None) -> List[ChunkResult]:
        """Chunk plain text (fallback for non-Deepgram input).

        This method provides a basic chunking implementation for plain text
        input. For proper meeting transcript chunking with speaker metadata,
        use chunk_from_deepgram() instead.

        Args:
            text: Plain text to chunk
            source_metadata: Optional metadata (not used for plain text chunking)

        Returns:
            List of ChunkResult objects without speaker metadata

        Note:
            This is a fallback implementation. For meeting transcripts,
            prefer chunk_from_deepgram() which preserves speaker boundaries.
        """
        if text is None:
            raise ValueError("text cannot be None")

        if not text or not text.strip():
            return []

        chunks = []
        char_offset = 0
        chunk_index = 0

        while char_offset < len(text):
            # Extract chunk with target size
            end_offset = min(char_offset + self.chunk_size, len(text))
            chunk_text = text[char_offset:end_offset]

            # Create chunk result
            chunks.append(
                ChunkResult(
                    text_content=chunk_text,
                    char_offset_start=char_offset,
                    char_offset_end=end_offset,
                    chunk_index=chunk_index,
                    metadata={},
                )
            )

            # Move to next chunk with overlap
            char_offset += self.chunk_size - self.chunk_overlap
            chunk_index += 1

        return chunks

    def chunk_from_deepgram(
        self,
        deepgram_response: dict,
        participant_mapping: dict = None
    ) -> List[ChunkResult]:
        """Chunk Deepgram utterances while preserving speaker boundaries.

        This is the primary method for chunking meeting transcripts. It processes
        Deepgram's utterance array and combines them intelligently into chunks
        that respect speaker boundaries.

        Args:
            deepgram_response: Full Deepgram API response with structure:
                {
                    "results": {
                        "utterances": [
                            {
                                "speaker": 0,
                                "start": 0.5,
                                "end": 5.2,
                                "transcript": "Hello everyone..."
                            },
                            ...
                        ]
                    }
                }
            participant_mapping: Optional dict mapping speaker IDs to names:
                {0: "Alice Smith", 1: "Bob Jones"}

        Returns:
            List of ChunkResult objects with preserved speaker metadata:
                - metadata.speaker: "Speaker 0", "Speaker 1", etc.
                - metadata.timestamp: "HH:MM:SS" formatted time
                - metadata.speaker_name: Actual name if mapping provided

        Raises:
            ValueError: If deepgram_response is None or missing required fields
            KeyError: If utterances don't have required fields (speaker, start, transcript)

        Example:
            >>> response = {...}  # Deepgram response
            >>> mapping = {0: "Alice", 1: "Bob"}
            >>> chunks = chunker.chunk_from_deepgram(response, mapping)
            >>> print(f"Created {len(chunks)} chunks")
            >>> print(f"First chunk speaker: {chunks[0].metadata['speaker_name']}")
        """
        if deepgram_response is None:
            raise ValueError("deepgram_response cannot be None")

        # Extract utterances from Deepgram response
        try:
            utterances = deepgram_response.get("results", {}).get("utterances", [])
        except AttributeError:
            raise ValueError(
                "Invalid deepgram_response format: must be dict with 'results.utterances'"
            )

        if not utterances:
            return []

        chunks = []
        current_chunk_utterances = []
        current_chunk_length = 0
        chunk_index = 0
        overall_char_offset = 0

        for utterance in utterances:
            # Validate required fields
            if not all(key in utterance for key in ["speaker", "start", "transcript"]):
                raise KeyError(
                    f"Utterance missing required fields (speaker, start, transcript): {utterance}"
                )

            utterance_text = utterance["transcript"]
            utterance_length = len(utterance_text)

            # If adding this utterance would exceed chunk_size and we have content,
            # create a chunk (unless it's the first utterance in chunk)
            if (
                current_chunk_length + utterance_length > self.chunk_size
                and current_chunk_utterances
            ):
                # Create chunk from accumulated utterances
                chunk_result = self._create_chunk_from_utterances(
                    current_chunk_utterances,
                    chunk_index,
                    overall_char_offset,
                    participant_mapping,
                )
                chunks.append(chunk_result)

                # Update offset and index
                overall_char_offset += len(chunk_result.text_content)
                chunk_index += 1

                # Calculate overlap: keep last few utterances
                overlap_utterances = self._calculate_overlap_utterances(
                    current_chunk_utterances
                )
                current_chunk_utterances = overlap_utterances
                current_chunk_length = sum(
                    len(u["transcript"]) for u in current_chunk_utterances
                )

            # Add current utterance to chunk
            current_chunk_utterances.append(utterance)
            current_chunk_length += utterance_length

        # Create final chunk if there are remaining utterances
        if current_chunk_utterances:
            chunk_result = self._create_chunk_from_utterances(
                current_chunk_utterances,
                chunk_index,
                overall_char_offset,
                participant_mapping,
            )
            chunks.append(chunk_result)

        return chunks

    def _create_chunk_from_utterances(
        self,
        utterances: List[dict],
        chunk_index: int,
        char_offset_start: int,
        participant_mapping: dict = None
    ) -> ChunkResult:
        """Create a ChunkResult from a list of utterances.

        Args:
            utterances: List of Deepgram utterance dicts
            chunk_index: Index of this chunk in the sequence
            char_offset_start: Starting character offset in full transcript
            participant_mapping: Optional speaker ID to name mapping

        Returns:
            ChunkResult with combined text and first utterance's metadata
        """
        # Combine utterance texts
        combined_text = " ".join(u["transcript"] for u in utterances)

        # Extract metadata from first utterance (represents chunk start)
        first_utterance = utterances[0]
        speaker_id = first_utterance["speaker"]
        start_time = first_utterance["start"]

        metadata = {
            "speaker": f"Speaker {speaker_id}",
            "timestamp": self._format_timestamp(start_time),
            "speaker_name": participant_mapping.get(speaker_id) if participant_mapping else None,
        }

        return ChunkResult(
            text_content=combined_text,
            char_offset_start=char_offset_start,
            char_offset_end=char_offset_start + len(combined_text),
            chunk_index=chunk_index,
            metadata=metadata,
        )

    def _calculate_overlap_utterances(self, utterances: List[dict]) -> List[dict]:
        """Calculate which utterances to keep for overlap.

        Args:
            utterances: List of utterances from previous chunk

        Returns:
            List of utterances to keep for overlap (from end of list)
        """
        overlap_utterances = []
        overlap_length = 0

        # Work backwards from the end to accumulate overlap
        for utterance in reversed(utterances):
            utterance_length = len(utterance["transcript"])
            if overlap_length + utterance_length <= self.chunk_overlap:
                overlap_utterances.insert(0, utterance)
                overlap_length += utterance_length
            else:
                break

        return overlap_utterances

    @staticmethod
    def _format_timestamp(seconds: float) -> str:
        """Convert seconds to HH:MM:SS format.

        Args:
            seconds: Time in seconds (can be float)

        Returns:
            Formatted timestamp string "HH:MM:SS"

        Example:
            >>> MeetingChunker._format_timestamp(65.5)
            '00:01:05'
            >>> MeetingChunker._format_timestamp(3661.0)
            '01:01:01'
        """
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
